name: Deploy2
on: [push, pull_request]
  
#   push:
#     branches: [ "master" ] 
#   pull_request:
#     branches: [ "master" ] 
  #schedule:    
   # - cron: "*/5 * * * *"
jobs:  
  build:  
    name: Run Web App using
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
#     if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: Echo
        
        uses: actions/checkout@v1
      - run: echo "hello"
      
  testing:
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')

    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: path 
        uses: actions/checkout@v1
      - run: pwd
      
  calling:
    
    needs: build 
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')

#     if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.ref == 'refs/heads/master'}} 
#     container:
#       image: openjdk:8-jdk-slim
    steps:
      - name: list all in the folder
        
        uses: actions/checkout@v1
      - run: |
          ls -lrt
