name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]
  #schedule:
   # - cron: "*/5 * * * *"
jobs:
  build:
    name: Run Web App 
    runs-on: ubuntu-latest
#     if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }} 
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: Echo
        
        uses: actions/checkout@v1
      - run: echo "hello"
      
  testing:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: path 
        uses: actions/checkout@v1
      - run: pwd
      
  calling:
    
    needs: build 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: test
#     if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }} 
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: list all in the folder
        
        uses: actions/checkout@v1
      - run: |
          ls -lrt
